(function(){'use strict';
const KEY='controle_clientes_v3';
const $=id=>document.getElementById(id);
const today=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const addDays=(iso,n)=>{const d=new Date(iso+'T00:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const id=()=>window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const clean=s=>String(s??'').trim();
const esc=s=>clean(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>{if(!d)return 'Sem data';const [y,m,day]=d.split('-');return `${day}/${m}/${y}`};
const initial=[
['EMPRO','2026-08-28','3280',1],['CIBELDE','2026-08-28','3255',1],['OSVALDO','2026-08-31','3312',1],['CALEBE','2026-08-31','3257',1],['SQUADRA PER','2026-09-01','',1],['RONALDO TUR','2026-09-01','',0],['PACIENTE','2026-09-01','3238',0],['GRIPMASTER','2026-09-02','',0],['PRIMASTER','2026-09-02','',0],['LEONARDO','2026-09-02','',0],['CEI NAZIR MG','2026-09-02','',1],['JOAO CARLOS','2026-09-03','3317',0],['ESCOLA LUZ','2026-09-03','3252',1],['ADRIANO VITO','2026-09-04','3318',0],['BERCARIO','2026-09-08','3303',0],['BURGUIES INT','2026-09-08','',0],['GIUSER','2026-09-09','?',0],['PATRICIA G','2026-10-09','',1],['CAIO ALZAR','2026-10-09','3332',0],['PERCLIANO','2026-10-09','3329',0],['NARA','2026-09-11','',0],['SQUADRA CA','2026-09-14','',0],['FRIGORIFICO','2026-10-17','',0],['ASMIR','2026-08-27','',1],['SERGIO','2026-08-08','3308',1],['AGIS','2026-09-04','',0],['JEFFERSON','2026-09-11','',1],['BRYAN','2026-08-28','3291',1]
];
let clients;
try{clients=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){clients=null}
if(!Array.isArray(clients)){clients=initial.map(x=>({id:id(),name:x[0],date:x[1],os:x[2],done:!!x[3],notes:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));localStorage.setItem(KEY,JSON.stringify(clients))}
function save(){localStorage.setItem(KEY,JSON.stringify(clients))}
function showToast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function list(){const q=clean($('search').value).toLowerCase(),st=$('status').value,p=$('period').value,t=today(),end=addDays(t,7);return clients.filter(c=>{if(st==='pending'&&c.done)return false;if(st==='done'&&!c.done)return false;if(p==='today'&&c.date!==t)return false;if(p==='week'&&(!c.date||c.date<t||c.date>end))return false;if(p==='overdue'&&(!c.date||c.date>=t||c.done))return false;if(p==='nodate'&&c.date)return false;return !q||`${c.name} ${c.os} ${c.notes}`.toLowerCase().includes(q)}).sort((a,b)=>Number(a.done)-Number(b.done)||(a.date||'9999-99-99').localeCompare(b.date||'9999-99-99')||a.name.localeCompare(b.name,'pt-BR'))}
function render(){const t=today();const data=list();$('tbody').innerHTML=data.map(c=>{let dc=!c.done&&c.date===t?'today':!c.done&&c.date&&c.date<t?'overdue':'';return `<tr class="${c.done?'doneRow':''}"><td class="donecol"><input class="rowdone" type="checkbox" data-toggle="${esc(c.id)}" ${c.done?'checked':''} aria-label="Marcar ${esc(c.name)} como concluído"></td><td><span class="client ${c.done?'strike':''}">${esc(c.name)}</span></td><td>${c.date?`<span class="datebadge ${dc}">${fmt(c.date)}</span>`:'<span class="muted">—</span>'}</td><td>${c.os?`<span class="osbadge">${esc(c.os)}</span>`:'<span class="muted">—</span>'}</td><td>${c.notes?esc(c.notes):'<span class="muted">—</span>'}</td><td class="actionsCell"><button class="smallbtn" data-edit="${esc(c.id)}">Editar</button><button class="smallbtn danger" data-delete="${esc(c.id)}">Excluir</button></td></tr>`}).join('');$('empty').hidden=data.length!==0;document.querySelector('.tablewrap').style.display=data.length?'':'none';$('count').textContent=`${data.length} ${data.length===1?'registro':'registros'}`;
$('sTotal').textContent=clients.length;$('sPending').textContent=clients.filter(c=>!c.done).length;$('sToday').textContent=clients.filter(c=>!c.done&&c.date===t).length;$('sOverdue').textContent=clients.filter(c=>!c.done&&c.date&&c.date<t).length;$('sDone').textContent=clients.filter(c=>c.done).length}
function openForm(c){$('form').reset();$('editId').value=c?c.id:'';$('modalTitle').textContent=c?'Editar cliente':'Novo cliente';if(c){$('name').value=c.name;$('date').value=c.date;$('os').value=c.os;$('notes').value=c.notes;$('done').checked=c.done}$('dialog').showModal();setTimeout(()=>$('name').focus(),30)}
$('newBtn').onclick=()=>openForm();$('emptyNew').onclick=()=>openForm();$('closeBtn').onclick=()=>$('dialog').close();$('cancelBtn').onclick=()=>$('dialog').close();
$('form').onsubmit=e=>{e.preventDefault();const name=clean($('name').value);if(!name){$('name').focus();return}const payload={name,date:$('date').value,os:clean($('os').value),notes:clean($('notes').value),done:$('done').checked,updatedAt:new Date().toISOString()};const eid=$('editId').value;if(eid){const i=clients.findIndex(c=>c.id===eid);if(i>=0)clients[i]={...clients[i],...payload}}else clients.push({id:id(),createdAt:new Date().toISOString(),...payload});save();render();$('dialog').close();showToast('Cadastro salvo com sucesso.')};
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const c=clients.find(x=>x.id===edit.dataset.edit);if(c)openForm(c)}if(del){const c=clients.find(x=>x.id===del.dataset.delete);if(c&&confirm(`Excluir "${c.name}"?`)){clients=clients.filter(x=>x.id!==c.id);save();render();showToast('Cadastro excluído.')}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-toggle]')){const c=clients.find(x=>x.id===e.target.dataset.toggle);if(c){c.done=e.target.checked;c.updatedAt=new Date().toISOString();save();render();showToast(c.done?'Cliente concluído.':'Cliente reaberto.')}}});
$('search').oninput=render;$('status').onchange=render;$('period').onchange=render;
document.querySelectorAll('[data-stat]').forEach(b=>b.onclick=()=>{const v=b.dataset.stat;if(v==='all'){$('status').value='all';$('period').value='all'}else if(v==='pending'){$('status').value='pending';$('period').value='all'}else if(v==='done'){$('status').value='done';$('period').value='all'}else{$('status').value='pending';$('period').value=v==='today'?'today':'overdue'}render()});
$('backupBtn').onclick=()=>{download('controle-de-clientes-backup.json',JSON.stringify(clients,null,2),'application/json');showToast('Backup criado.')};$('restoreBtn').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data)||data.some(c=>!clean(c.name)))throw new Error();clients=data.map(c=>({id:c.id||id(),name:clean(c.name),date:c.date||'',os:clean(c.os),notes:clean(c.notes),done:!!c.done,createdAt:c.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}));save();render();showToast('Backup restaurado.')}catch(err){alert('Arquivo de backup inválido.')}e.target.value=''};
$('exportBtn').onclick=()=>{const csv=[['Cliente','Data prevista','OS','Concluído','Observação'],...clients.map(c=>[c.name,c.date?fmt(c.date):'',c.os,c.done?'Sim':'Não',c.notes])].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');download('clientes.csv','\ufeff'+csv,'text/csv;charset=utf-8');showToast('CSV exportado.')};
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
render();
})();
