(function(){'use strict';
const KEY='controle_clientes_v4', $=id=>document.getElementById(id);
const today=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const addDays=(s,n)=>{const d=new Date(s+'T00:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const makeId=()=>crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const clean=s=>String(s??'').trim(), esc=s=>clean(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>{if(!d)return 'Sem data';const [y,m,day]=d.split('-');return `${day}/${m}/${y}`};
const periodLabel=v=>({all:'Todos os clientes',today:'Clientes previstos para hoje',week:'Próximos 7 dias',overdue:'Clientes atrasados',nodate:'Clientes sem data'})[v];
const normalize=c=>({id:c.id||makeId(),name:clean(c.name||c.nome_cliente),date:c.date||c.data_prevista||'',os:clean(c.os),notes:clean(c.notes||c.observacao),done:!!(c.done??c.concluido),createdAt:c.createdAt||new Date().toISOString(),updatedAt:c.updatedAt||new Date().toISOString()});
let clients=[];try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x))clients=x.map(normalize)}catch(e){}
function save(){localStorage.setItem(KEY,JSON.stringify(clients))}
if(!clients.length&&Array.isArray(window.CLIENTES_INICIAIS)){clients=window.CLIENTES_INICIAIS.map(x=>normalize({name:x[0],date:x[1],os:x[2],done:x[3]}));save()}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>{e.classList.remove('show');e.onclick=null},2400)}
function getList(){const q=clean($('search').value).toLowerCase(),st=$('status').value,p=$('period').value,t=today(),end=addDays(t,7);return clients.filter(c=>{if(st==='pending'&&c.done||st==='done'&&!c.done)return false;if(p==='today'&&c.date!==t)return false;if(p==='week'&&(!c.date||c.date<t||c.date>end))return false;if(p==='overdue'&&(!c.date||c.date>=t||c.done))return false;if(p==='nodate'&&c.date)return false;return !q||`${c.name} ${c.os} ${c.notes}`.toLowerCase().includes(q)}).sort((a,b)=>Number(a.done)-Number(b.done)||(a.date||'9999-99-99').localeCompare(b.date||'9999-99-99')||a.name.localeCompare(b.name,'pt-BR'))}
function stats(t){$('sTotal').textContent=clients.length;$('sPending').textContent=clients.filter(c=>!c.done).length;$('sToday').textContent=clients.filter(c=>!c.done&&c.date===t).length;$('sOverdue').textContent=clients.filter(c=>!c.done&&c.date&&c.date<t).length;$('sDone').textContent=clients.filter(c=>c.done).length}
function active(){document.querySelectorAll('[data-stat]').forEach(x=>x.classList.remove('active'));const st=$('status').value,p=$('period').value,k=p==='today'?'today':p==='overdue'?'overdue':st==='pending'?'pending':st==='done'?'done':p==='all'?'all':'';document.querySelector(`[data-stat="${k}"]`)?.classList.add('active')}
function render(){const t=today(),list=getList();$('tbody').innerHTML=list.map(c=>{const dc=!c.done&&c.date===t?'today':!c.done&&c.date&&c.date<t?'overdue':'';return `<tr class="${c.done?'doneRow':''}"><td class="check-col"><input class="rowdone" type="checkbox" data-toggle="${esc(c.id)}" ${c.done?'checked':''} aria-label="Concluir ${esc(c.name)}"></td><td><span class="client ${c.done?'strike':''}">${esc(c.name)}</span></td><td>${c.date?`<span class="datebadge ${dc}">${fmt(c.date)}</span>`:'<span class="datebadge nodate">Sem data</span>'}</td><td>${c.os?`<span class="osbadge">${esc(c.os)}</span>`:'<span class="muted">—</span>'}</td><td>${c.notes?esc(c.notes):'<span class="muted">—</span>'}</td><td class="actionsCell"><button class="smallbtn" data-edit="${esc(c.id)}">Editar</button><button class="smallbtn danger" data-delete="${esc(c.id)}">Excluir</button></td></tr>`}).join('');$('empty').hidden=!!list.length;document.querySelector('.table-scroll').style.display=list.length?'':'none';$('count').textContent=`${list.length} ${list.length===1?'registro':'registros'}`;$('context').textContent=periodLabel($('period').value);stats(t);active()}
function openForm(c){$('form').reset();$('editId').value=c?.id||'';$('modalTitle').textContent=c?'Editar cliente':'Novo cliente';if(c){$('name').value=c.name;$('date').value=c.date;$('os').value=c.os;$('notes').value=c.notes;$('done').checked=c.done}$('dialog').showModal();setTimeout(()=>$('name').focus(),30)}
function clearFilters(){ $('search').value='';$('status').value='all';$('period').value='all';render();$('search').focus() }
$('newBtn').onclick=()=>openForm();$('emptyNew').onclick=()=>openForm();$('closeBtn').onclick=()=>$('dialog').close();$('cancelBtn').onclick=()=>$('dialog').close();$('clearFilters').onclick=clearFilters;
$('form').onsubmit=e=>{e.preventDefault();const name=clean($('name').value);if(!name){toast('Informe o nome do cliente.');$('name').focus();return}const data={name,date:$('date').value,os:clean($('os').value),notes:clean($('notes').value),done:$('done').checked,updatedAt:new Date().toISOString()},eid=$('editId').value;if(eid){const i=clients.findIndex(c=>c.id===eid);if(i>=0)clients[i]={...clients[i],...data}}else clients.push({id:makeId(),createdAt:new Date().toISOString(),...data});save();render();$('dialog').close();toast(eid?'Cadastro atualizado.':'Cliente cadastrado.')};
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const c=clients.find(x=>x.id===edit.dataset.edit);if(c)openForm(c)}if(del){const c=clients.find(x=>x.id===del.dataset.delete);if(c&&confirm(`Excluir "${c.name}"?`)){clients=clients.filter(x=>x.id!==c.id);save();render();const old={...c},el=$('toast');toast('Excluído. Clique aqui para desfazer.');el.onclick=()=>{clients.push(old);save();render();el.onclick=null;toast('Exclusão desfeita.')}}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-toggle]')){const c=clients.find(x=>x.id===e.target.dataset.toggle);if(c){c.done=e.target.checked;c.updatedAt=new Date().toISOString();save();render();toast(c.done?'Cliente concluído.':'Cliente reaberto.')}}});
$('search').oninput=render;$('status').onchange=render;$('period').onchange=render;document.querySelectorAll('[data-stat]').forEach(b=>b.onclick=()=>{const v=b.dataset.stat;if(v==='all'){$('status').value='all';$('period').value='all'}else if(v==='pending'){$('status').value='pending';$('period').value='all'}else if(v==='done'){$('status').value='done';$('period').value='all'}else{$('status').value='pending';$('period').value=v}render()});
$('backupBtn').onclick=()=>{download('controle-de-clientes-backup.json',JSON.stringify(clients,null,2),'application/json');toast('Backup criado.')};$('restoreBtn').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data)||data.some(c=>!clean(c.name||c.nome_cliente)))throw 0;if(!confirm(`Restaurar ${data.length} cadastro(s)? A agenda atual será substituída.`))return;clients=data.map(normalize);save();render();toast('Backup restaurado.')}catch(x){alert('Arquivo de backup inválido.')}finally{e.target.value=''}};
$('exportBtn').onclick=()=>{const rows=[['Cliente','Data prevista','OS','Concluído','Observação'],...clients.map(c=>[c.name,c.date?fmt(c.date):'',c.os,c.done?'Sim':'Não',c.notes])];download('clientes.csv','\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('CSV exportado.')};
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus();$('search').select()}if(e.key==='Escape'&&$('dialog').open)$('dialog').close();if(e.key.toLowerCase()==='n'&&!$('dialog').open&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='TEXTAREA')openForm()});
render();
})();
